### ISSUE TITLE
Variables not working properly in stylesheet

### ISSUE THREAD

**Issue by jdev082** [JaydenDev/SimplicityCSS#1]
I am aware of this bug, this is in beta! I am working on a fix, but don't know where to start.

**Comment by MystPi** [comment]
It's not a bug; you're not using them quite right.

### Setting variables
Set the variables in the `:root` element.
```css
:root {
  --var-1: var-value;
  --var-2: var-value;
  /* etc. */
}
```
### Getting variables
Just use the `var()` function:
```css
element {
  property: var(--var-1);
  property-2: var(--var-2);
  /* etc. */
}
```
That's basically it! You can take a look at [DreamCSS](https://github.com/MystPi/dreamcss/blob/main/src/dream.css)'s source if you need any more help.
